[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lm-tournament-eval"
version = "0.0.2"
description = "A framework for evaluating language models using dataset tournaments."
readme = "README.md"
authors = [
    {name="Richard Kelley", email="richard.kelley@gmail.com"},
    {name="Duncan Wilson", email="todo@todo.com"}
]
license = { "text" = "MIT" }

dependencies = [
    "datasets>=2.0.0",
    "torch>=2.0.0",
    "hflm>=0.0.7"
]

[project.scripts]
lm-tournament-eval = "lm_tournament_eval.scripts.lm_tournament_eval.__main__:run_tournament"
lm_tournament_eval = "lm_tournament_eval.scripts.lm_tournament_eval.__main__:run_tournament"
lm-roundrobin-eval = "lm_tournament_eval.scripts.lm_roundrobin_eval.__main__:run_roundrobin_eval"
lm_roundrobin_eval = "lm_tournament_eval.scripts.lm_roundrobin_eval.__main__:run_roundrobin_eval"